//
//  StyleKitName.h
//  ProjectName
//
//  Created by AuthorName on 14/10/14.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>



@interface StyleKitName : NSObject

// Colors
+ (UIColor*)color;

// Shadows
+ (NSShadow*)shadow;

//// In trial version of PaintCode, the code generation is limited to one canvas

// Drawing Methods
+ (void)drawCanvas1;

@end



@interface NSShadow (PaintCodeAdditions)

+ (instancetype)shadowWithColor: (UIColor*)color offset: (CGSize)offset blurRadius: (CGFloat)blurRadius;
- (void)set;

@end
